### ISSUE TITLE
Modal Integration

### ISSUE THREAD

**Issue by slavakurilyak** [BennyKok/comfyui-deploy#1]
As per [README](https://github.com/BennyKok/comfyui-deploy#status--timeline), it is "possible to set up a clean environment via Salad, **Modal**, etc."

Modal is perfectly suited to deploy comfyui-deploy, pun intended, as it can "scale to infinity, and to zero." In other words, Modal can handle deployment and scaling of ComfyUI by @comfyanonymous.

Check out their image, video, and 3D use cases [here](https://modal.com/use-cases/image-video-3d).

Modal became [generally available on Oct 10](https://modal.com/blog/general-availability-and-series-a), or 74 days ago.

For coding inspiration, check out [a1111_webui.py](https://github.com/modal-labs/modal-examples/blob/main/06_gpu_and_ml/stable_diffusion/a1111_webui.py) by @modal-labs or [running Stable Diffusion WebUI using Modal](https://blog.14nigo.net/2023/05/stablediffusionwebuionmodal.html) by 14nigo.net.

**Comment by BennyKok** [comment]
Will definitely start looking into this in the following weeks. Meanwhile if anyone wanted to help out would be really appreciated.!

**Comment by Ehesh** [comment]
Looks nice but the modal storage... $2 per GB/mo...

**Comment by BennyKok** [comment]
> Looks nice but the modal storage... $2 per GB/mo...

Im curious where can I find this in the pricing plan page? I couldn't find the information about storage cost on modal

**Comment by aksh-at** [comment]
We also have an [example](https://github.com/modal-labs/modal-examples/blob/main/06_gpu_and_ml/stable_diffusion/comfy_ui.py) for running comfy UI directly over websockets :)

**Comment by BennyKok** [comment]
@aksh-at Yes! Already intergrated! YOU guys have been awesome in the slack group! shout out to Jonathon for the great example. Also looking to integrate more with modal, like optimizing for cold start and stuff, would love to have a technical deep dive with you guys afterward, to clear up my understanding with modal's infra and how can I better optimize for the current implementation.

**Comment by xllusion-dong** [comment]
How to support API in modal？
