### ISSUE TITLE
No Text input for 'External Text (ComfyUI Deploy)' component

### ISSUE THREAD

**Issue by flov** [BennyKok/comfyui-deploy#3]
I can't seem to find a `Clip Text Encode` component that takes `Text` as input as shown inside the video in the Readme. It simply isn't there and I can't seem to find it.

<img width="1009" alt="Screenshot 2023-12-31 at 18 22 40" src="https://github.com/BennyKok/comfyui-deploy/assets/96314/7688ae2f-9797-44d1-ae17-0fc2a5a4f83f">

**Comment by BennyKok** [comment]
You will need to right click on the CLIP Text Encode and convert the clip text to input
