### ISSUE TITLE
Cannot find downloaded model in the check point model list

### ISSUE THREAD

**Issue by qren0neu** [BennyKok/comfyui-deploy#49]
Hello there, I'm new to the comfy deploy and I'm encountering some problems.

**The workflow I'm using:** 

The Example SDXL Turbo workflow, I cloned it.

**Problem I met:**

I added Juggernaut V10 in to storage, the path is `checkpoints/Juggernaut-X-RunDiffusion-NSFW.safetensors`.

The model usl is: https://huggingface.co/RunDiffusion/Juggernaut-X-v10/resolve/main/Juggernaut-X-RunDiffusion-NSFW.safetensors

it successfully downloaded, but when I'm trying to use it in the workflow, I cannot find it in the dropdown list of the checkpoint.

My question is, am I doing it in the wrong way, or did I missed some step? What should I do to add a model from Hugging Face and use it in the checkpoint?

Thanks!

**Comment by BennyKok** [comment]
Are you using the hosted version? let me know in discord if it is.

**Comment by omarei-omoto** [comment]
hit refresh on the models, and wait till it says private models reloaded

**Comment by qren0neu** [comment]
Thanks, during the time the issue come out I also sent a message on discord so I got that fixed.
