### ISSUE TITLE
Love

### ISSUE THREAD

**Issue by naripok** [BennyKok/comfyui-deploy#50]
I freaking love you project, man!

I just came to say this. I wanted you to know.

It saved me so much time from having to craft cogs to run flows on replicate.

Freaking awesome!

Thank you for this!

**Comment by naripok** [comment]
Sorry for the spam!

I'm closing it now.

Love!!!

**Comment by BennyKok** [comment]
Appreciated dude! ❤️ Let us know if any problems in discord, feel free!
